title: Anveshana
email: r.mythreyi.rr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A daily dose of curiosity
baseurl: "/anveshana" # the subpath of your site, e.g. /blog
url: "https://a-doctor-and-a-phd.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom collections
collections:
  questions:
    output: true
    permalink: /questions/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "questions"
    values:
      layout: "question"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom variables
learning_journal:
  date_format: "%b %-d, %Y"

github_username: a-doctor-and-a-phd
repository_name: anveshana
